sudo: required
services:
  - docker

before_install:
  - docker build -t adamgouldmig/react-tests -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true adamgouldmig/react-tests npm run test

after_success:
  - docker build -t adamgouldmig/multi-client ./client
  - docker build -t adamgouldmig/multi-nginx ./nginx
  - docker build -t adamgouldmig/multi-server ./server
  - docker build -t adamgouldmig/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push adamgouldmig/multi-client
  - docker push adamgouldmig/multi-nginx
  - docker push adamgouldmig/multi-server
  - docker push adamgouldmig/multi-worker

# Example AWS deploy steps.
# deploy:
#   edge: true #force travis to use v2 of dpl script
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "multi-docker"
#   env: "MultiDocker-env"
#   bucket_name: "elasticbeanstalk-us-west-2-432432434455"
#   bucket_path: "docker-multi" # Same as app
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY #This should come from travis. Not in SC!
#   secret_access_key: $AWS_SECRET_KEY #This should come from travis. Not in SC!
